apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote-deployment
  namespace: local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: 502447419870.dkr.ecr.us-east-1.amazonaws.com/vote-j2:latest
        name: vote
        ports:
        - containerPort: 80
          name: vote
